# Generated by Django 3.1.2 on 2020-11-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Kompaniyaning Manzili')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('website', models.CharField(max_length=255, verbose_name="Qo'shimcha website manzili")),
                ('googleApi', models.CharField(max_length=500, verbose_name='Google kartadagi manzil')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Xat jonatuvchining ismi')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Murojat Xati')),
            ],
        ),
    ]
