# Generated by Django 3.1.2 on 2020-11-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Hodimning rasmi')),
                ('fullName', models.CharField(max_length=100, verbose_name='Hodimning ismi va Familiyasi')),
                ('profession', models.CharField(max_length=100, verbose_name='Hodimning vazifasi')),
                ('about', models.TextField(verbose_name='Hodim haqida qisqacha malumot')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPersonContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pochta yoki ichtimoiy tarmoq nomi')),
                ('url', models.URLField(verbose_name='Pochtaning manzili')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teamperson')),
            ],
        ),
    ]
