# Generated by Django 3.1.2 on 2020-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Dizayn rasmi'),
        ),
    ]
