# Generated by Django 3.1.2 on 2020-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201103_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/customer', verbose_name='Klientning rasmi')),
                ('text', models.TextField(verbose_name='klientning fikri')),
                ('fullName', models.CharField(max_length=150, verbose_name='Klientning ism-sharifi')),
                ('companyName', models.CharField(max_length=255, verbose_name='klientning firmasi')),
            ],
        ),
    ]
