# Generated by Django 3.1.2 on 2020-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='About qismiga matn')),
                ('img', models.ImageField(upload_to='images/about', verbose_name='About qismiga rasm')),
            ],
        ),
    ]
