# Generated by Django 3.1.2 on 2020-11-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/blog', verbose_name='Maqola uchun rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Maqolaning mavzusi')),
                ('letter', models.TextField(verbose_name='Maqola')),
                ('date', models.DateField(auto_now=True, verbose_name='Maqola yozilgan sana')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Maqola muallifi')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Izoh qoldiruvchining ismi')),
                ('email', models.EmailField(max_length=100, verbose_name='Izoh qoldiruvchining e-maili')),
                ('comment', models.TextField(verbose_name='Izoh')),
                ('date', models.DateField(auto_now=True, verbose_name='Izoh yozilgan sana')),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blogletter', verbose_name='Maqola mavzusi')),
            ],
        ),
    ]
