# Generated by Django 3.1.2 on 2020-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogletter_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogletter',
            name='slug',
            field=models.SlugField(default='salom', max_length=160, verbose_name='Ssilka uchun'),
            preserve_default=False,
        ),
    ]
