# Generated by Django 3.1.2 on 2020-11-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blogletter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teamperson', verbose_name='Maqola muallifi'),
        ),
    ]
