# Generated by Django 3.1.2 on 2020-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201106_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('about', models.TextField(verbose_name='Xizmat haqida')),
            ],
        ),
    ]
