# Generated by Django 3.1.2 on 2020-11-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('sidetitle', models.CharField(max_length=255, verbose_name='Yon tomondagi Mavzu')),
                ('text', models.TextField(verbose_name='Matn')),
                ('img', models.ImageField(upload_to='images/homeheader/', verbose_name='rasm')),
            ],
        ),
    ]
